
# html lang
language: zh-CN

# main menu navigation
menu:
  #Home: /
  #About: /about
  #Contact: /contact
  #Archives: /archives

footer:
  owner:
    enable: true
    since: 2020
  custom_text: 
  ICP: # Chinese ICP License
    enable: false
    url:
    text:

favicon: /img/favicon.ico

busuanzi:
  enable: true

# Fancybox support
fancybox: true

# Comments System
comments:
  use: 

# Gitalk Comments
# https://github.com/gitalk/gitalk
gitalk:
  owner: 
  repo: 
  admin: 
  clientID: 
  clientSecret: 

# disqus
# https://disqus.com/
disqus:
  shortname: 